#!/usr/bin/env python3
"""Generate INVENTORY.md — the AUTHORITATIVE, anti-hallucination ground truth.

Reads the real source-of-truth files and emits a single Markdown doc listing the
ONLY valid robot keys, environments, anchors, templates, scenes, and RL tasks.
This file is what the `inventory` skill (and OpenClaw memory) cite so a local
model never invents robots/scenes that don't exist.

    python3 gen_inventory.py            # write INVENTORY.md next to this script
    python3 gen_inventory.py --check    # exit 1 if INVENTORY.md is stale (CI/precommit)

Run it after editing catalog.yaml / environments.yaml / templates / envs_registry.
"""
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
CLAW = os.environ.get("ISAAC_CLAW_DIR", os.path.dirname(os.path.dirname(HERE)))
CATALOG = os.path.join(CLAW, "agents", "core", "assets", "catalog.yaml")
ENVS_TPL = os.path.join(CLAW, "isaac_sim", "templates", "environments.yaml")
TPL_DIR = os.path.join(CLAW, "isaac_sim", "templates")
SCENES = os.path.join(CLAW, "isaac_sim", "scenes")
REGISTRY = os.path.join(CLAW, "isaac_lab", "envs_registry.json")
OUT = os.path.join(HERE, "INVENTORY.md")


def _yaml(p):
    with open(p) as f:
        return yaml.safe_load(f) or {}


def build():
    cat = _yaml(CATALOG).get("categories", {}) or {}
    L = []
    L.append("# isaac-claw — INVENTORY (authoritative ground truth)")
    L.append("")
    L.append("> GENERATED by `skills/inventory/gen_inventory.py` from the real catalog,")
    L.append("> templates, scenes, and registry. **Do not edit by hand.** Regenerate after")
    L.append("> changing those files. This is the ONLY valid list — see the rules at the end.")
    L.append("")

    # ---- robots (catalog: robots + humanoids categories) ----
    robots, humanoids = cat.get("robots", {}) or {}, cat.get("humanoids", {}) or {}
    L.append("## Robot keys you may spawn (catalog)")
    L.append("These are the EXACT keys for `claw open --robot <key>`. No others exist.")
    L.append("")
    L.append("### Humanoids / bipeds")
    for k, e in humanoids.items():
        e = e or {}
        L.append(f"- `{k}` — z={e.get('start_z','?')}, {e.get('drive','?')}, tags={e.get('tags',[])}")
    L.append("")
    L.append("### Quadrupeds, mobile, arms, hands, aerial")
    for k, e in robots.items():
        e = e or {}
        L.append(f"- `{k}` — z={e.get('start_z','?')}, {e.get('drive','?')}, tags={e.get('tags',[])}")
    L.append("")

    # ---- environments (only those wired in environments.yaml are openable) ----
    envs = _yaml(ENVS_TPL)
    L.append("## Environments you may OPEN right now")
    L.append("`claw open --env <name>`. Only these are wired + have a scene on disk.")
    L.append("")
    for name, e in envs.items():
        anchors = ", ".join((e.get("anchors") or {}).keys())
        L.append(f"- `{name}` — scene `{e.get('scene','?')}`, "
                 f"default anchor `{e.get('default_anchor','?')}`, anchors: [{anchors}]")
    L.append("")

    # ---- environments registered in catalog but NOT yet openable ----
    cat_envs = cat.get("environments", {}) or {}
    not_open = [k for k in cat_envs if k not in envs]
    if not_open:
        L.append("### Catalog environments NOT yet openable")
        L.append("Listed in the catalog but missing an `environments.yaml` entry and/or a built")
        L.append("scene USD. Do NOT offer these as openable until wired:")
        L.append("")
        for k in not_open:
            L.append(f"- `{k}` (needs an environments.yaml entry + scene USD)")
        L.append("")

    # ---- composite templates ----
    L.append("## Templates (preset env + robots)")
    L.append("`claw open --template <name>`.")
    L.append("")
    for f in sorted(os.listdir(TPL_DIR)) if os.path.isdir(TPL_DIR) else []:
        if f.endswith(".yaml") and f != "environments.yaml":
            t = _yaml(os.path.join(TPL_DIR, f))
            rb = ", ".join(r.get("robot", "?") for r in t.get("robots", []))
            L.append(f"- `{f[:-5]}` — env `{t.get('environment','?')}`, robots: [{rb}]")
    L.append("")

    # ---- scenes on disk ----
    L.append("## Scene USDs actually on disk")
    scenes = sorted(p for p in os.listdir(SCENES)
                    if p.endswith((".usd", ".usda", ".usdc"))) if os.path.isdir(SCENES) else []
    L.append(", ".join(f"`{s}`" for s in scenes) if scenes
             else "_(none built — regenerate with isaac_sim/scripts/build_warehouse.py)_")
    L.append("")

    # ---- trainable robots (registry) — DISTINCT from spawnable ----
    reg = json.load(open(REGISTRY)).get("environments", []) if os.path.exists(REGISTRY) else []
    train_robots = sorted({e.get("robot", "?") for e in reg})
    L.append(f"## Trainable robots ({len(train_robots)}) — NOT spawnable")
    L.append("These robots appear in RL TASK ids (train them with `claw train`). They are a")
    L.append("DIFFERENT list from the spawnable catalog above — `claw open --robot <x>` does")
    L.append("NOT accept these. Never merge this list into the spawnable robots.")
    L.append("")
    L.append(", ".join(f"`{r}`" for r in train_robots))
    L.append("")

    # ---- RL tasks ----
    tasks = [e["id"] for e in reg]
    L.append(f"## RL training task ids ({len(tasks)} total) — for `claw train --task <id>`")
    L.append("Use these EXACT ids. Tasks containing `Velocity` are locomotion.")
    L.append("")
    for t in tasks:
        L.append(f"- `{t}`")
    L.append("")

    # ---- props & sensors (spawnable assets, not robots) ----
    for grp, title in (("props", "Props (assets, not robots)"),
                       ("sensors", "Sensors (assets, not robots)")):
        items = cat.get(grp, {}) or {}
        if items:
            L.append(f"## {title}")
            L.append(", ".join(f"`{k}`" for k in items))
            L.append("")

    # ---- hard rules ----
    L.append("## HARD RULES (read before answering 'what is available?')")
    L.append("1. The ONLY valid robot/env/task names are the ones ABOVE (or from a live")
    L.append("   `claw robots`/`templates`/`scenes`/`envs`). If a name is not here, it does")
    L.append("   NOT exist — never invent one (no `jetbot`, no made-up scenes).")
    L.append("2. `omx-control` and `soarm-control` are skills for PHYSICAL robot arms")
    L.append("   (Robotis OMX, SO-101) — they are NOT Isaac Sim robots. Do not list them as")
    L.append("   spawnable sim robots when asked about the simulation inventory.")
    L.append("3. Prefer running the live command (`claw robots` etc.) and report its output")
    L.append("   verbatim. Use this file only as the fallback when the server is down.")
    L.append("4. An environment is 'openable' only if it appears under 'Environments you may")
    L.append("   OPEN right now'. Catalog-only environments are not openable yet.")
    return "\n".join(L) + "\n"


def main():
    content = build()
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != content:
            print("INVENTORY.md is STALE — run: python3 gen_inventory.py", file=sys.stderr)
            return 1
        print("INVENTORY.md up to date.")
        return 0
    with open(OUT, "w") as f:
        f.write(content)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
