#!/usr/bin/env python3
"""Compound place action: down + gripper_open + up."""

import json
import sys
import time
import urllib.request

HOST = "host.openshell.internal"
HTTP_PORT = 5560

PLACE_SEQUENCE = [
    {"action": "down", "params": {"distance": 0.15}},
    {"action": "gripper_open", "params": {}},
    {"action": "up", "params": {"distance": 0.15}},
]


def send_cmd(cmd):
    url = f"http://{HOST}:{HTTP_PORT}/command"
    data = json.dumps(cmd).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    urllib.request.urlopen(req, timeout=5)


def main():
    print("Executing PLACE sequence...")
    for step in PLACE_SEQUENCE:
        send_cmd(step)
        print(f"  -> {step['action']} {step.get('params', {})}")
        time.sleep(2.0)
    print("PLACE complete.")


if __name__ == "__main__":
    main()
